devsearch/urls.py
import imp
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')), 
    path('', include('users.urls')), 
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from sys import prefix
from turtle import update
from django.urls import path
from . import views

prefix =  "users."

urlpatterns = [
    path('', views.index, name=prefix+"index"),
    path('show/<str:id>', views.show, name=prefix+"show"),
    path('account', views.account, name=prefix+"account"),
    path('account/edit', views.accountEdit, name=prefix+"account.edit"),
    path('login', views.loginUser, name="login"),
    path('logout', views.logoutUser, name="logout"),
    path('regisiter', views.registerUser, name="register"),

    path('query/', views.query, name="query"),
    path('search/<str:searchfor>', views.search, name="search"),

    path('skill/', views.skill, name=prefix+'skill'),
    path('skill/update/<str:id>', views.skillUpdate, name=prefix+'skill.update'),
    path('skill/delete/<str:id>', views.skillDelete, name=prefix+'skill.delete'),
    path('inbox', views.inbox, name='inbox'),
    path('message/<str:id>', views.message, name='message'),
    path('send-message/<str:id>', views.sendMessage, name='send-message'),
]

projects/models.py
from cProfile import Profile
from operator import mod
from re import L
from statistics import mode
from wsgiref.simple_server import demo_app
from django.db import models
from users.models import Profile
import uuid

# Create your models here.

class Project(models.Model):
    owner = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    demo_link = models.CharField(max_length=2000, null=True, blank=True)
    featured_image = models.ImageField(null=True, blank=True, default="resibee.png")
    source_link = models.CharField(max_length=2000, null=True, blank=True)
    tags = models.ManyToManyField('Tag', blank=True)
    vote_totel = models.IntegerField(default=0, null=True, blank=True)
    vote_ratio = models.IntegerField(default=0, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    @property
    def calculateVoteRatio(self):
        reviews = self.review_set.all()
        upVotes = reviews.filter(value='up').count()
        totalVoutes = reviews.count()
        ratio = (upVotes / totalVoutes) * 100
        self.vote_ratio = ratio
        self.vote_totel = totalVoutes
        self.save()

    @property
    def revieweres(self):
        return self.review_set.all().values_list('owner__id', flat=True)

        

    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['-created_at']

class Review(models.Model):
    VOTE_TYPE = (
        ('up', 'Up Vote'),
        ('down', 'Down Vote'),
    )
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, verbose_name="User") 
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    body = models.TextField(null=True, blank=True)
    value = models.CharField(max_length=200, choices=VOTE_TYPE)
    created_at = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    class Meta:
        unique_together = [['owner', 'project']]

    def __str__(self):
        return self.value

class Tag(models.Model):
    name = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.name

users/models.py
import email
from email.policy import default
from enum import unique
from operator import mod
import profile
from statistics import mode
from xml.parsers.expat import model
from django.db import models
from django.contrib.auth.models import User
import uuid
from django.db.models import signals
from django.dispatch import receiver

from django.forms import CharField

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=256, null=True, blank=True)
    username = models.CharField(max_length=256, null=True, blank=True)
    location = models.CharField(max_length=256, null=True, blank=True)
    email = models.EmailField(max_length=254, null=True, blank=True)
    job = models.CharField(max_length=256, blank=True, null=True)
    short_intro = models.CharField(max_length=254, null=True, blank=True)
    bio = models.TextField(null=True, blank=True)
    profile_image = models.ImageField(upload_to="profiles", null=True, blank=True, default="profiles/profile.png")
    social_linkedin = models.CharField(max_length=256, null=True, blank=True)
    social_youtube = models.CharField(max_length=256, null=True, blank=True)
    social_github = models.CharField(max_length=256, null=True, blank=True)
    social_twitter = models.CharField(max_length=256, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return str(self.user.username)

class Skill(models.Model):        
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=256)
    description = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.name)

class Post(models.Model):
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    title = models.CharField(max_length=256, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.title)
        

class Message(models.Model):
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    sender = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True)
    receiver = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True, related_name="messages")
    name = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(max_length=200, null=True, blank=True)
    is_readed = models.BooleanField(default=False, null=True)
    subject = models.CharField(max_length=200)
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.body)

    class Meat:
        ordering = ['is_readed', '-created_at']

users/forms.py
from dataclasses import fields
from pyexpat import model
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Message, Profile, Skill

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'username', 'email', 'password1', 'password2']
        labels = {
            'first_name': 'Name'
        }

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({"class": 'form-control'})    

class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['name', 'username', 'location', 'email', 'job', 'short_intro', 'bio', 'profile_image', 'social_linkedin', 'social_github', 'social_youtube', 'social_twitter'] 

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'})
            if name == 'bio':
                field.widget.attrs.update({'style': 'height: 60px'})

class SkillForm(ModelForm):
    class Meta:
        model = Skill
        fields = '__all__'
        exclude = ['owner']

    def __init__(self, *args, **kwargs):
        super(SkillForm, self).__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'})
        self.fields['description'].widget.attrs.update({'style': 'min-height: 15px !important'})

class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ['name', 'email', 'subject', 'body']

    def __init__(self, *args, **kwargs):
        super(MessageForm, self).__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'})

users/views.py
from ast import Try
from contextlib import redirect_stderr
import imp
import profile
from urllib import request
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
# from django.contrib.auth.forms import UserCreationForm 
from .forms import CustomUserCreationForm, MessageForm, ProfileForm
from django.contrib import messages
from django.db.models import Q
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from .models import Message, Profile, Skill
from .models import Post as Po
from .service import Get, Post
from projects.models import Project, Tag

# Create your views here.

def show(request, id):
    profile = Profile.objects.get(id=id)
    topSkills = profile.skill_set.exclude(description__exact="")
    otherSkills = profile.skill_set.filter(description="")
    context = {"profile": profile, "topSkills": topSkills, 'otherSkills': otherSkills}
    return render(request, 'users/show.html', context)

def index(request):
    profiles = Profile.objects.all()
    page = 1
    if request.GET:
        page = request.GET['page']
    result = 4
    paginator = Paginator(profiles, result)
    try:
        profiles = paginator.page(page)
    except EmptyPage:
        page = Paginator.num_pages
    except PageNotAnInteger:
        page = Paginator.num_pages
    profiles = paginator.page(page)
    context = {'profiles': profiles, 'paginator': paginator}
    return render(request, 'users/index.html', context)

def registerUser(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            login(request, user)
            messages.success(request, 'User account is created')
            return redirect('users.index')

    form = CustomUserCreationForm()
    context = {'form': form}
    return render(request, 'users/register.html', context) 

def loginUser(request):
    if request.user.is_authenticated:
        return redirect('users.index')

    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        try:
            user = User.objects.get(username=username)
        except:
            print('User does not exist')
        user = authenticate(request, )
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            messages.success(request, "Welcome "+username)
            return redirect('users.index')
        else:
            messages.error(request, 'username or password is in correct')

    return render(request, 'users/login.html') 

def logoutUser(request):
    logout(request)
    return redirect('login')

@login_required(login_url='login')
def account(request):
    user = User.objects.all()
    print(user)
    profile = request.user.profile
    skills = profile.skill_set.all()
    context = {'profile': profile, 'skills': skills}
    return render(request, 'users/account.html', context)

@login_required(login_url='login')
def accountEdit(request):
    if request.method == "GET":
        return Get.accontEditForm(request)    
    if request.method == "POST":
        return Post.accontEditForm(request)

@login_required(login_url="login")        
def skill(request):
    if request.method == "GET":
        return Get.skill(request)    
    if request.method == "POST":
        return Post.skill(request)
        
@login_required(login_url='login')
def skillUpdate(request, id):
    if request.method == "GET":
        return Get.skillUpdate(request, id)
    if request.method == "POST":
        return Post.skillUpdate(request, id)
        
@login_required(login_url='login')
def skillDelete(request, id):
        return Get.skillDelete(request, id)

def query(request):
    posts = Po.objects.get(title="django")
    posts.title = 'Laravel'
    posts.description = 'Laravel is an MVC framework'
    posts.save()
    return HttpResponse(posts)

@login_required(login_url='login')
def inbox(request):
    profile = request.user.profile
    messagesModel = profile.messages.all()
    noOfUnreadedMessages = messagesModel.filter(is_readed=False).count()
    context = {'messagesModel': messagesModel, "noOfUnreadedMessages": noOfUnreadedMessages}
    return render(request, 'messages/inbox.html', context)


def search(request, searchfor):
    if searchfor == 'users':
        search = request.GET['value']
        skills =  Skill.objects.filter(name__iexact=search)
        tags = Tag.objects.filter(name__icontains=search)
        profiles = Profile.objects.distinct().filter(
            Q(name__icontains=search) | Q(bio__icontains=search) | Q(skill__in=skills)
            )  
        projects = Project.objects.filter(Q(title__contains=search) | Q(tags__in=tags))
        context = { "profiles": profiles, "skills": skills, "projects": projects }
        return render(request, 'ajax/porfile-search.html', context)
    return HttpResponse('No response')

@login_required(login_url='login')
def message(request, id):
    profile = request.user.profile
    message = profile.messages.get(id=id)
    if message.is_readed == False:
        message.is_readed = True
        message.save()
    context = {'message': message}
    return render(request, 'messages/message.html', context)


def sendMessage(request, id):
    profile = Profile.objects.get(id=id)
    messageForm = MessageForm()
    if request.method == "POST":
        form = MessageForm(request.POST)
        if form.is_valid(): 
            form = form.save(commit=False)
            form.sender = request.user.profile
            form.receiver = profile
            form.save()
            messages.success(request, 'Message has send successfully')
            return redirect('users.show', id=id)
    context = {"profile": profile, "messageForm": messageForm}
    return render(request, 'messages/message.html', context)

users/templates/users/account.html
{% extends 'main.html' %} {% block content %}

<section class="section">
  <div class="section-header">
    <h1>{{ profile.name }}'s profile</h1>
    <div class="section-header-breadcrumb">
      <div class="breadcrumb-item active"><a href="{% url 'users.index' %}">Dashboard</a></div>
      {% comment %} <div class="breadcrumb-item">Profile</div> {% endcomment %}
    </div>
  </div>
  <div class="section-body">
    <div class="row mt-sm-4">
      <div class="col-12 col-md-12 col-lg-5">
        <div class="card profile-widget">
          <div class="profile-widget-header">
            <img
              alt="image"
              src="{{ profile.profile_image.url }}"
              class="rounded-circle profile-widget-picture"
            />
            <div class="profile-widget-items">
              <div class="profile-widget-item">
                <div class="profile-widget-item-label">Posts</div>
                <div class="profile-widget-item-value">187</div>
              </div>
              <div class="profile-widget-item">
                <div class="profile-widget-item-label">Followers</div>
                <div class="profile-widget-item-value">6,8K</div>
              </div>
              <div class="profile-widget-item">
                <div class="profile-widget-item-label">Following</div>
                <div class="profile-widget-item-value">2,1K</div>
              </div>
            </div>
          </div>
          <div class="profile-widget-description">
            <div class="profile-widget-name">
              {{ profile.username }}
              <div class="text-muted d-inline font-weight-normal">
                <div class="slash"></div>
                Web Developer
              </div>
            </div>


            <div class="summary-item">
                <h6 class="mt-3 mb-4" style="display:flex; justify-content:space-between"><div>Technologies known <span class="text-muted">({{ profile.skill_set.count }})</span></div><div><a href="{% url 'users.skill' %}">Add more</a></div></h6>
                <ol style="" class="list-unstyled list-unstyled-border">
                    {% for skill in profile.skill_set.all %}
                  <li class="media">
                    <div class="media-body">
                      <div class="media-title" style="display:flex; justify-content: space-between;">
                        <a href="#">{{forloop.counter}}.{{ skill.name }}</a> 
                        <div>
                          <a href="{% url 'users.skill.update' skill.id %}"><i class="fas fa-edit"></i></a>
                          <a href="{% url 'users.skill.delete' skill.id %}"><i class="fas fa-trash"></i></a>
                        </div>
                      </div>
                      <div class="text-small text-muted">{{ skill.description }}</div>
                    </div>
                  </li>
                  {% endfor %}
                </ol>
              </div>

            

          </div>
          <div class="card-footer text-center">
            <div class="font-weight-bold mb-2">Follow Ujang On</div>
            <a href="#" class="btn btn-social-icon btn-facebook mr-1">
              <i class="fab fa-facebook-f"></i>
            </a>
            <a href="#" class="btn btn-social-icon btn-twitter mr-1">
              <i class="fab fa-twitter"></i>
            </a>
            <a href="#" class="btn btn-social-icon btn-github mr-1">
              <i class="fab fa-github"></i>
            </a>
            <a href="#" class="btn btn-social-icon btn-instagram">
              <i class="fab fa-instagram"></i>
            </a>
          </div>
        </div>
      </div>
      <div class="col-12 col-md-12 col-lg-7">
        <div class="card">
          <form method="post" class="needs-validation" novalidate="">
            <div class="card-header" style="justify-content: space-between">
              <h4>Profile</h4>
              <a href="{% url 'users.account.edit' %}" class="btn btn-primary">Edit</a>
            </div>
            <div class="card-body">
              <div class="row">
                <div class="form-group col-md-6 col-12">
                  <label>Name</label>
                  <p>{{ profile.name }}</p>
                </div>
                <div class="form-group col-md-6 col-12">
                  <label>Username</label>
                  <p>{{ profile.username }}</p>
                </div>
                <div class="form-group col-md-6 col-12">
                  <label>Location</label>
                  <p>{{ profile.location }}</p>
                </div>
                <div class="form-group col-md-6 col-12">
                  <label>Email</label>
                  <p>{{ profile.email }}</p>
                </div>
                <div class="form-group col-md-12 col-12">
                  <label>Short intro</label>
                  <p>{{ profile.short_intro }}</p>
                </div>
                <div class="form-group col-md-12 col-12">
                  <label>Bio</label>
                  <p>{{ profile.bio }}</p>
                </div>
            </div>
          </form>
        </div>
      </div>


      
    </div>
    
    <h2 class="section-title">My projects</h2>
  </div>
  <div class="row">
    {% for project in profile.project_set.all %}
          <div class="col-12 col-md-4 col-lg-4">
              <article class="article article-style-c">
              <div class="article-header">
                  <div
                  class="article-image"
                  data-background="{{ project.featured_image.url }}"
                  ></div>
              </div>
              <div class="article-details">
                  <div class="article-category">{{ project.created_at }}</div>
                  <div class="article-title">
                  <h2 style="display:flex; justify-content: space-between;">
                      <a href="{% url 'project' project.id %}">{{ project.title }}</a>
                  </h2>
                  </div>
                  <p>{{ project.description }}</p>
                  <div class="article-user">
                  <div class="selectgroup selectgroup-pills">
                      {% for tag in project.tags.all %}
                      <label class="selectgroup-item">
                      <input
                          type="checkbox"
                          name="value"
                          checked
                          value="Ruby"
                          disabled
                          class="selectgroup-input"
                      />
                      <a class="selectgroup-button">{{ tag.name }}</a>
                      </label>
                      {% endfor %}
                  </div>
                  </div>
              </div>
              <div class="card-footer" style="display:flex; justify-content: flex-end">
                <a class="text text-success"  href="{% url 'update-project' project.id %}">Update</a> &nbsp&nbsp
                <a class="text text-danger"  href="{% url 'delete-project' project.id %}">Delete</a>
              </div>

              </article>
          </div>
{% endfor %}
  </div>
</section>

{% endblock content %}

users/templates/users/edit-account.html
{% extends 'main.html' %} {% block content %}

<section class="section">
  <div class="section-header">
    <h1>{{ profile.name }}'s profile</h1>
    <div class="section-header-breadcrumb">
      <div class="breadcrumb-item active"><a href="{% url 'users.index' %}">Dashboard</a></div>
      {% comment %} <div class="breadcrumb-item">Profile</div> {% endcomment %}
    </div>
  </div>
  <div class="section-body">
    
      <form method="POST" enctype="multipart/form-data" class="needs-validation" novalidate="">
          <div class="card-body">
              <div class="row">
              {% csrf_token %}
              {% for filed in form %}
              <div class="form-group col-md-6 col-12">
                <label>{{ filed.label }}</label>
                  {{filed}}
                </div>
                {% endfor %}
            </div>
              <input type="submit" class="btn btn-primary" value="Update" />
        </div>
      </form>

  </div>
  </div>
</section>

{% endblock content %}

users/templates/users/show.html
{% extends 'main.html' %} {% block content %}

<section class="section">
  <div class="section-header">
    <h1>{{ profile.name }}'s profile</h1>
    <div class="section-header-breadcrumb">
      <div class="breadcrumb-item active"><a href="{% url 'users.index' %}">Dashboard</a></div>
      {% comment %} <div class="breadcrumb-item">Profile</div> {% endcomment %}
    </div>
  </div>
  <div class="section-body">
    <div class="row mt-sm-4">
      <div class="col-12 col-md-12 col-lg-5">
        <div class="card profile-widget">
          <div class="profile-widget-header">
            <img
              alt="image"
              src="{{ profile.profile_image.url }}"
              class="rounded-circle profile-widget-picture"
            />
            <div class="profile-widget-items">
              <div class="profile-widget-item">
                <div class="profile-widget-item-label">Posts</div>
                <div class="profile-widget-item-value">187</div>
              </div>
              <div class="profile-widget-item">
                <div class="profile-widget-item-label">Followers</div>
                <div class="profile-widget-item-value">6,8K</div>
              </div>
              <div class="profile-widget-item">
                <div class="profile-widget-item-label">Following</div>
                <div class="profile-widget-item-value">2,1K</div>
              </div>
            </div>
          </div>
          <div class="profile-widget-description">
            <div class="profile-widget-name">
              {{ profile.username }}
              <div class="text-muted d-inline font-weight-normal">
                <div class="slash"></div>
                Web Developer
              </div>
            </div>


            <div class="summary-item">
                <h6 class="mt-3">Technologies known <span class="text-muted">({{ profile.skill_set.count }})</span></h6>
                <ol style="" class="list-unstyled list-unstyled-border">
                    {% for skill in topSkills %}
                  <li class="media">
                    {% comment %} <a href="#">
                      <img alt="image" class="mr-3 rounded" width="50" src="../assets/img/products/product-4-50.png">
                    </a> {% endcomment %}
                    <div class="media-body">
                      <div class="media-title"><a href="#">{{ skill.name }}</a></div>
                      <div class="text-small text-muted">{{ skill.description }}</div>
                    </div>
                  </li>
                  {% endfor %}
                </ol>
              </div>


              
          <div class="article-user" style="margin: 5px">
            <div class="selectgroup selectgroup-pills">
              {% for skill in otherSkills %}
              <label class="selectgroup-item">
                <input
                  type="checkbox"
                  name="value"
                  checked
                  value="Ruby"
                  disabled
                  class="selectgroup-input"
                />
                <a class="selectgroup-button">{{ skill.name }}</a>
              </label>
              {% endfor %}
            </div>
          </div>

            

          </div>
          <div class="card-footer text-center">
            <div class="font-weight-bold mb-2">Follow Ujang On</div>
            <a href="#" class="btn btn-social-icon btn-facebook mr-1">
              <i class="fab fa-facebook-f"></i>
            </a>
            <a href="#" class="btn btn-social-icon btn-twitter mr-1">
              <i class="fab fa-twitter"></i>
            </a>
            <a href="#" class="btn btn-social-icon btn-github mr-1">
              <i class="fab fa-github"></i>
            </a>
            <a href="#" class="btn btn-social-icon btn-instagram">
              <i class="fab fa-instagram"></i>
            </a>
          </div>
          <div class="card-footer text-center">
            <a href="{% url 'send-message' profile.id %}" class="btn btn-primary">Message</a>
          </div>
        </div>
      </div>
      <div class="col-12 col-md-12 col-lg-7">
        <div class="card">
          <form method="post" class="needs-validation" novalidate="">
            <div class="card-header">
              <h4>Profile</h4>
            </div>
            <div class="card-body">
              <div class="row">
                <div class="form-group col-md-6 col-12">
                  <label>Name</label>
                  <p>{{ profile.name }}</p>
                </div>
                <div class="form-group col-md-6 col-12">
                  <label>Username</label>
                  <p>{{ profile.username }}</p>
                </div>
                <div class="form-group col-md-6 col-12">
                  <label>Location</label>
                  <p>{{ profile.location }}</p>
                </div>
                <div class="form-group col-md-6 col-12">
                  <label>Email</label>
                  <p>{{ profile.email }}</p>
                </div>
                <div class="form-group col-md-12 col-12">
                  <label>Short intro</label>
                  <p>{{ profile.short_intro }}</p>
                </div>
                <div class="form-group col-md-12 col-12">
                  <label>Bio</label>
                  <p>{{ profile.bio }}</p>
                </div>
            </div>
          </form>
        </div>
      </div>


      
    </div>
    
    <h2 class="section-title">My projects</h2>
  </div>
  <div class="row">
    {% for project in profile.project_set.all %}
          <div class="col-12 col-md-4 col-lg-4">
              <article class="article article-style-c">
              <div class="article-header">
                  <div
                  class="article-image"
                  data-background="{{ project.featured_image.url }}"
                  ></div>
              </div>
              <div class="article-details">
                  <div class="article-category">{{ project.created_at }}</div>
                  <div class="article-title">
                  <h2>
                      <a href="{% url 'project' project.id %}">{{ project.title }}</a>
                  </h2>
                  </div>
                  <p>{{ project.description }}</p>
                  <div class="article-user">
                  <div class="selectgroup selectgroup-pills">
                      {% for tag in project.tags.all %}
                      <label class="selectgroup-item">
                      <input
                          type="checkbox"
                          name="value"
                          checked
                          value="Ruby"
                          disabled
                          class="selectgroup-input"
                      />
                      <a class="selectgroup-button">{{ tag.name }}</a>
                      </label>
                      {% endfor %}
                  </div>
                  </div>
              </div>
              </article>
          </div>
{% endfor %}
  </div>
</section>

{% endblock content %}